<?php // Generated by Nvu + HandCoder ?>
<!DOCTYPE html>
<html lang="fr">
<head>

  <meta name="description"
 content="Tout sur le comitï¿½ territorial <?php echo $titre;?> : Prï¿½sentation du comitï¿½ (Bureau; adresse; contact mel; contact site officiel du comitï¿½); les effectifs; les palmarï¿½s nationaux; les palmarï¿½s territoriaux et l'ensemble des clubs composant le comitï¿½ avec un lien pour accï¿½der aux diffï¿½rents clubs.">
  <meta name="keywords"
 content="comitï¿½ Bourgogne,Comite Midi Pyrenees de Rugby,Comite Midi Pyrenees Rugby,Stade toulousain,Colomiers,FFR,Rugby,Federation,Franï¿½aise,Rugbyman,Rugbymen,Sport,Ballon,Ovale,">
  <meta name="classification" content="Sport,Rugby">
  <meta name="resource-type" content="document">
  <meta name="copyright" content="Comite Midi Pyrenees de Rugby">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="author" content="Equipe Onepip">
  <meta name="robots" content="All">
  <link type="text/css" rel="stylesheet" href="ligne1.css">
  <link type="text/css" rel="stylesheet" href="lienNoir.css">
  <title>Mise a  jour des resultats</title>
</head>
<body>
<div align="center">
<table height="639" width="1100">
  <tbody>
    <tr bordercolor="#FFFFFF" align="center" valign="middle">
      <td colspan="3" height="74"><?php include("page_image_al.php"); ?>
      </td>
    </tr>
    <tr>
      <td colspan="3"><?php include("01ligne.php"); ?> </td>
    </tr>
    <tr align="center" bgcolor="#000000" valign="middle">
      <td align="center" bgcolor="#006699" height="505" valign="top"
 width="225">
      <div align="center">
      <p align="center"><?php include("01gauche.php"); ?><b><font
 color="#000000" size="5"> </font></b></p>
      </div>
      </td>
      <td text="#000000" link="#000000" vlink="#000000" alink="#000000"
 bgcolor="#ffffff" height="505" valign="top" width="550" bordercolor="#66CC33"> 
        <div align="center">
      <p><font color="#000000">&nbsp;</font></p>
          <p><b><font size="6" color="#000000">MISE A JOUR DES RESULTATS </font></b></p>
          <p><font size="6" color="#000000"><b>ET DES CLASSEMENTS</b></font></p>
          <p>&nbsp;</p>
          <p><big style="color: rgb(255, 0, 0); font-weight: bold;"><big><b><font size="4" face="Arial, Helvetica, sans-serif">Saississez 
            vous m&ecirc;me les r&eacute;sultats de votre club <br>
            et mettez le classement &agrave; jour en temps r&eacute;el.</font></b></big></big><br
 style="font-weight: bold;">
            <br>
          </p>
          <div style="text-align: left;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;<br>
            &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;<font face="Arial, Helvetica, sans-serif">&nbsp;<a style="color: rgb(15, 15, 15);" href="pageOutil.php"><font size="4">Comment 
            faire ?</font></a></font></span><font size="4" face="Arial, Helvetica, sans-serif"><br style="font-weight: bold;">
            <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
            &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br>
            &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a
 style="color: rgb(9, 12, 9);" href="pagecontrole.php">Qui controle l'exactitude 
            des scores saisis ?</a></span><br style="font-weight: bold;">
            <br style="font-weight: bold;">
            <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a
 style="color: rgb(0, 0, 0);" href="pageEquipe2.php">Le disposif peut il &ecirc;tre 
            utilis&eacute; pour les &eacute;quipes II ?</a></span><br style="font-weight: bold;">
            <br style="font-weight: bold;">
            <span style="font-weight: bold;"><a style="color: rgb(0, 0, 0);"
 href="pageSMS.php"><span style="font-weight: bold;"> <font color="#FFFFFF">DD</font>Comment 
            retrouver les liens d'une semaine &agrave; l'autre ?</span></a></span></font><br
 style="font-weight: bold;">
      <span style="font-weight: bold;"> <br>
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;</span>
       <hr /><hr />
      <br>
            <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
            <b><font size="5" color="#FF0000">&nbsp;&nbsp;&nbsp; <big><big><big>Comment 
            faire ?</big></big></big></font></b></span><br>
      <br>
            <div style="text-align: left;"> 
              <p><font color="#000000">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
                &nbsp;&nbsp;&nbsp; <font size="4" face="Arial, Helvetica, sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                Demandez par SMS au<b> 06.82.24.70.57</b> ou par courriel<br>
                (<b>francefinalesrugby@free. fr</b>), un lien qui vous permettra 
                </font></font><font color="#000000" size="4" face="Arial, Helvetica, sans-serif">durant 
                toute la saison, de saisir les r&eacute;sultats et de mettre &agrave; 
                jour le classement<span
 style="font-weight: bold;">.</span><br>
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;Il suffit simplement de pr&eacute;ciser 
                le nom du club dans le message.&nbsp;&nbsp; En cliquant sur le 
                lien vous obtenez un &eacute;cran de ce type</font><font color="#000000">.<br>
                <font face="Arial, Helvetica, sans-serif" size="4">cette mise 
                &agrave; jour peur &ecirc;tre effectu&eacute;e &agrave; partir 
                d'un smartphone, d'une tablette, d'un PC ou d'un Apple</font></font><font face="Arial, Helvetica, sans-serif" size="4">.<br>
                </font><br>
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
                &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; <img
 style="border: 1px solid ; width: 400px; height: 558px;" alt=""
 src="images/smart/ecran1.bmp"><br>
              </p>
              <hr /><hr />
            </div>
          </div>
          <div style="text-align: left;">
            <p><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;</span>&nbsp;<font face="Arial, Helvetica, sans-serif" size="4">&nbsp;</font><font face="Arial, Helvetica, sans-serif" size="4"><font color="#000000">Vous 
              saississez scores et bonus comme indiqu&eacute; puis vous Valider.&nbsp; 
              Un &eacute;cran de confirmation vous est propos&eacute;</font></font><br>
              <br>
            </p>
            <div style="text-align: center;"><img
 style="border: 1px solid ; width: 364px; height: 486px;" alt=""
 src="images/smart/ecan2.bmp"><br>
      <br><hr /><hr />
              <font color="#000000" face="Arial, Helvetica, sans-serif" size="4">Si 
              vous confirmez&nbsp;vous accedez &agrave; l'application smarphone 
              avec r&eacute;sultats et classement &agrave; jour, sinon vous pouvez 
              modifier votre saisie.</font><br>
      </div>
      <br>
      <div style="text-align: center;"><img
 style="border: 1px solid ; width: 372px; height: 598px;" alt=""
 src="images/smart/ecran3.bmp"><br>
      </div>
            <div align="center"><br>
              <br>
              <br>
              <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;</span><b><font color="#FF0000" face="Arial, Helvetica, sans-serif" size="5">Essayez, 
              &ccedil;a n'engage &agrave; rien !!!</font></b><br>
              <font color="#FF0000" size="5"><b><br>
              <font face="Arial, Helvetica, sans-serif">Envoyez tout simplement,<br>
              par SMS au <font color="#000000">06.82.24.70.57</font> <br>
              le nom de votre club</font></b></font><br>
            </div>
          </div>
      <br>
      <br>
      </div>
      </td>
      <td bgcolor="#006699" height="505" valign="top" width="225">
      <p><?php include("00droite.php"); ?> </p>
      </td>
    </tr>
    <tr bordercolor="#000000">
      <th colspan="3" bgcolor="#ffffff" height="78" valign="top">
      <table border="1" bordercolor="#006699" width="100%">
        <tbody>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("comitebas.php"); ?></font></div>
            </td>
          </tr>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("pub1.php"); ?></font></div>
            </td>
          </tr>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("bas.php"); ?></font></div>
            </td>
          </tr>
        </tbody>
      </table>
      </th>
    </tr>
  </tbody>
</table>
</div>
</body>
</html>
