<?php // Generated by Nvu + HandCoder ?>
<!DOCTYPE html>
<html lang="fr">
<head>

  <meta name="description"
 content="Tout sur le comit� territorial <?php echo $titre;?> : Pr�sentation du comit� (Bureau; adresse; contact mel; contact site officiel du comit�); les effectifs; les palmar�s nationaux; les palmar�s territoriaux et l'ensemble des clubs composant le comit� avec un lien pour acc�der aux diff�rents clubs.">
  <meta name="keywords"
 content="comit� Bourgogne,Comite Midi Pyrenees de Rugby,Comite Midi Pyrenees Rugby,Stade toulousain,Colomiers,FFR,Rugby,Federation,Fran�aise,Rugbyman,Rugbymen,Sport,Ballon,Ovale,">
  <meta name="classification" content="Sport,Rugby">
  <meta name="resource-type" content="document">
  <meta name="copyright" content="Comite Midi Pyrenees de Rugby">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="author" content="Equipe Onepip">
  <meta name="robots" content="All">
  <link type="text/css" rel="stylesheet" href="../../ligne1.css">
  <link type="text/css" rel="stylesheet" href="../../lienNoir.css">
  <title>Mise à jour des resultats</title>
</head>
<body>
<div align="center">
<table height="639" width="1100">
  <tbody>
    <tr bordercolor="#FFFFFF" align="center" valign="middle">
      <td colspan="3" height="74"><?php include("../../images/page_image_al.php"); ?>
      </td>
    </tr>
    <tr>
      <td colspan="3"><?php include("../../01ligne.php"); ?> </td>
    </tr>
    <tr align="center" bgcolor="#000000" valign="middle">
      <td align="center" bgcolor="#006699" height="505" valign="top"
 width="225">
      <div align="center">
      <p align="center"><?php include("../../01gauche.php"); ?><b><font
 color="#000000" size="5"> </font></b></p>
      </div>
      </td>
      <td text="#000000" link="#000000" vlink="#000000" alink="#000000"
 bgcolor="#ffffff" height="505" valign="top" width="550">
      <div align="center">
      <p><font color="#000000">&nbsp;</font></p>
          <div style="text-align: left;">
            <p align="center"><b><font size="6" color="#000000">MISE A JOUR DES 
              RESULTATS </font></b></p>
            <p align="center"><font size="6" color="#000000"><b>ET DES CLASSEMENTS</b></font></p>
            <p align="center">&nbsp;</p>
            <p align="center"><big style="color: rgb(255, 0, 0); font-weight: bold;"><big><b><font size="4" face="Arial, Helvetica, sans-serif">Saississez 
              vous m&ecirc;me les r&eacute;sultats de votre club <br>
              et mettez le classement &agrave; jour en temps r&eacute;el.</font></b></big></big><br
 style="font-weight: bold;">
              <br>
            </p>
            <div style="text-align: left;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; 
              &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
              &nbsp;&nbsp;&nbsp; &nbsp;<br>
              &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;<font face="Arial, Helvetica, sans-serif">&nbsp;<a style="color: rgb(15, 15, 15);" href="pageOutil.php"><font size="4">Comment 
              faire ?</font></a></font></span><font size="4" face="Arial, Helvetica, sans-serif"><br style="font-weight: bold;">
              <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
              &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;<br>
              &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a
 style="color: rgb(9, 12, 9);" href="pagecontrole.php">Qui 
              controle l'exactitude des scores saisis ?</a></span><br style="font-weight: bold;">
              <br style="font-weight: bold;">
              <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a
 style="color: rgb(0, 0, 0);" href="../../pageEquipe2.php">Le disposif peut il &ecirc;tre 
              utilis&eacute; pour les &eacute;quipes II ?</a></span><br style="font-weight: bold;">
              <br style="font-weight: bold;">
              <span style="font-weight: bold;"><a style="color: rgb(0, 0, 0);"
 href="pageSMS.php"><span style="font-weight: bold;"> <font color="#FFFFFF">DD</font>Comment 
              retrouver les liens d'une semaine &agrave; l'autre ?</span></a></span></font></div>
          <br
 style="font-weight: bold;">
      <span style="font-weight: bold;"> <br>
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;</span>
        <hr /><hr />
      <br>
            <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
            &nbsp;&nbsp;<big><big><font color="#FF0000" size="4" face="Arial, Helvetica, sans-serif">&nbsp; 
            Le disposif peut il &ecirc;tre utilis&eacute; pour les &eacute;quipes 
            II ?</font><font color="#000000"><br>
            </font></big></big><font color="#000000"><br>
            </font></span> 
            <div style="text-align: center;"><font color="#000000" size="4" face="Arial, Helvetica, sans-serif">Oui, 
              biensur.<br>
              Il faut cependant un lien diff&eacute;rent de celui de l'&eacute;quipe 
              Une<span
 style="font-weight: bold;">.</span><br>
              <br>
              La distinction ne peut se faire qu'au niveau du premier &eacute;cran 
              <br>
              ou le mention &eacute;quipe II est surlign&eacute;e<br>
              <br>
              <span style="font-weight: bold;">Il faut donc demander 2 liens</span></font><br>
      <span style="font-weight: bold;"></span><br>
      <span style="font-weight: bold;"></span><span
 style="font-weight: bold;"><img style="width: 399px; height: 111px;"
 alt="" src="../../images/smart/ecran7.bmp"></span><br>
      <span style="font-weight: bold;"></span><br>
      <span style="font-weight: bold;"><img
 style="width: 398px; height: 111px;" alt=""
 src="../../images/smart/ecran6.bmp"></span></div>
      </div>
      <div style="text-align: left;"><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;</span><br>
      </div>
      <br>
      <br>
      </div>
      </td>
      <td bgcolor="#006699" height="505" valign="top" width="225">
      <p><?php include("../../00droite.php"); ?> </p>
      </td>
    </tr>
    <tr bordercolor="#000000">
      <th colspan="3" bgcolor="#ffffff" height="78" valign="top">
      <table border="1" bordercolor="#006699" width="100%">
        <tbody>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("../../comitebas.php"); ?></font></div>
            </td>
          </tr>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("../../pub/pub1.php"); ?></font></div>
            </td>
          </tr>
          <tr>
            <td>
            <div align="center"><font color="#000000"><?php include("../../bas.php"); ?></font></div>
            </td>
          </tr>
        </tbody>
      </table>
      </th>
    </tr>
  </tbody>
</table>
</div>
</body>
</html>
